### ISSUE TITLE
accessing the files path using the gid

### ISSUE THREAD

**Issue by 5cat** [WOo0W/aria2-ws-rs#1]
I'm trying to get the path of a file that was downloaded.

I have the gid of it, i went for the [get_files](https://docs.rs/aria2-ws/latest/aria2_ws/struct.Client.html#method.get_files) method but the [File](https://docs.rs/aria2-ws/latest/aria2_ws/response/struct.File.html) struct does not provide a way to get the path, I checked the [source code](https://github.com/WOo0W/aria2-ws-rs/blob/040b3f34fbed95e3c937911582fb9429e1b332b9/src/response.rs#L112) and the attributes are not pub.
The only way i thought of doing is putting the object in a formatted and string slice it until i get the path but that seems very unnatural.

Is there a more reasonable way of doing this?

I'm new to rust so let me know if I missed something.

**Comment by ComfyFluffy** [comment]
Thanks for the issue.

The fields in `File` should be public. I'm just forgot to make them pubic. I have checked all public structs in `response.rs` and made these fields public.

I will fix it and add some tests soon.

**Comment by ComfyFluffy** [comment]
Fixed in `0.3.0`.

**Comment by 5cat** [comment]
wow thank you : )
