### ISSUE TITLE
Issue with JSON Parsing Error in `tell_status` Function

### ISSUE THREAD

**Issue by pierrbt** [WOo0W/aria2-ws-rs#2]
Hello,

I hope this message finds you well. I'm encountering an issue while using the `aria2_ws` library in Rust, specifically with the `tell_status` function. I believe there might be an error related to JSON parsing, as I'm receiving the following error message:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Json { source: Error("invalid type: sequence, expected a string", line: 0, column: 0) }', src\main.rs:61:41
```

Here's a bit of context on what I'm trying to achieve: I'm building an application using Tauri and Rust, and I'm aiming to interface with the `aria2` daemon using the `aria2_ws` library. My goal is to interact with the daemon using functions like `add_magnet`, `info_downloads`, `info_download`, `pause_download`, and `resume_download`, in order to make easy the interface with the Javascript, using exposed functions and the IPC protocol.

I have a function `info_download` that aims to retrieve active downloads and display their information. Here's the code snippet for the function:

```rust
async fn info_download(client: &Client, gid: &str) {
    for x in client.tell_active().await.unwrap() {
        println!(
            "Download GID: {}, Status: {:?}, Progress: {}%, Speed: {}",
            x.gid,
            x.status,
            (x.completed_length / x.total_length) * 100,
            x.download_speed
        );
    }
}
```

However, when I call this function, I encounter the aforementioned error related to JSON parsing. I suspect there might be an issue with how the JSON data is being processed within the `tell_status` function.

I'd greatly appreciate any insights or suggestions you might have regarding this issue. If there's anything I can provide to help diagnose the problem or any steps I can take to resolve it, please let me know.

Thank you in advance for your assistance. Looking forward to your response.

Best regards,
Pierre

**Comment by ComfyFluffy** [comment]
In my testing, both `tell_active` and `tell_status` work for HTTP and torrent downloads, with aria2 version of 1.36.0. Can you offer more detail of your download test url, aria2 version, or a single rust program which can run on it own and reproduce this issue?
